version: '3.4'
x-common-variables: &common-variables
   POSTGRES_PASSWORD: example
   POSTGRES_DB: icp
   POSTGRES_USER: postgres
services:
  pgdb:
    image: postgres
    ports:
        - 5432:5432
    container_name: pgdb
    environment:
     <<: *common-variables
  collections:
    image: ${DOCKER_REGISTRY-}collections
    build:
      context: .
      dockerfile: Collections/Dockerfile
    environment:
      <<: *common-variables
      ASPNETCORE_ENVIRONMENT: Development
      COMPOSE: 
        -True
    depends_on:
        - pgdb
